//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Common.Utility.Tools.XmlDocumentor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorba.Common.Utility.Tools.XmlDocumentor.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}=.
        /// </summary>
        internal static string AttributeFormat {
            get {
                return ResourceManager.GetString("AttributeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:1.
        /// </summary>
        internal static string AttributeOptional {
            get {
                return ResourceManager.GetString("AttributeOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:1.
        /// </summary>
        internal static string AttributeRequired {
            get {
                return ResourceManager.GetString("AttributeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML attributes of {0}.
        /// </summary>
        internal static string AttributesTableCaption {
            get {
                return ResourceManager.GetString("AttributesTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , default: &quot;{0}&quot;.
        /// </summary>
        internal static string DefaultValuePostfix {
            get {
                return ResourceManager.GetString("DefaultValuePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string ElementFormat {
            get {
                return ResourceManager.GetString("ElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}.
        /// </summary>
        internal static string ElementOccurs {
            get {
                return ResourceManager.GetString("ElementOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML elements inside {0}.
        /// </summary>
        internal static string ElementsTableCaption {
            get {
                return ResourceManager.GetString("ElementsTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Enumeration.
        /// </summary>
        internal static string EnumHeading {
            get {
                return ResourceManager.GetString("EnumHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration values of {0}.
        /// </summary>
        internal static string EnumTableCaption {
            get {
                return ResourceManager.GetString("EnumTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example {0}.
        /// </summary>
        internal static string ExampleConfigCaption {
            get {
                return ResourceManager.GetString("ExampleConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Configuration.
        /// </summary>
        internal static string ExampleConfigHeading {
            get {
                return ResourceManager.GetString("ExampleConfigHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure .
        /// </summary>
        internal static string FigurePrefix {
            get {
                return ResourceManager.GetString("FigurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This chapter was automatically generated from {0} on {1:yyyy&apos;/&apos;MM&apos;/&apos;dd} by {2}..
        /// </summary>
        internal static string GeneratedChapterNote {
            get {
                return ResourceManager.GetString("GeneratedChapterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string GeneratedChapterNoteSize {
            get {
                return ResourceManager.GetString("GeneratedChapterNoteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of .
        /// </summary>
        internal static string ListOfChoicePrefix {
            get {
                return ResourceManager.GetString("ListOfChoicePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string ListOfChoiceSeparator {
            get {
                return ResourceManager.GetString("ListOfChoiceSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of .
        /// </summary>
        internal static string ListOfElementsPrefix {
            get {
                return ResourceManager.GetString("ListOfElementsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string RootElementRefPostfix {
            get {
                return ResourceManager.GetString("RootElementRefPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root element is .
        /// </summary>
        internal static string RootElementRefPrefix {
            get {
                return ResourceManager.GetString("RootElementRefPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string RootElementRefSeparator {
            get {
                return ResourceManager.GetString("RootElementRefSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Structure.
        /// </summary>
        internal static string StructureHeading {
            get {
                return ResourceManager.GetString("StructureHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table .
        /// </summary>
        internal static string TablePrefix {
            get {
                return ResourceManager.GetString("TablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Structure.
        /// </summary>
        internal static string XmlStructureHeading {
            get {
                return ResourceManager.GetString("XmlStructureHeading", resourceCulture);
            }
        }
    }
}
