// <auto-generated />
namespace Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Forms.Editors
{
    partial class WorkItemFieldEditorDialog
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(WorkItemFieldEditorDialog));
            this.FieldNameLabel = new System.Windows.Forms.Label();
            this.FieldNameTextBox = new System.Windows.Forms.TextBox();
            this.FieldValueLabel = new System.Windows.Forms.Label();
            this.FieldValueTextBox = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            // 
            // SubmitButton
            // 
            resources.ApplyResources(this.SubmitButton, "SubmitButton");
            // 
            // AbortButton
            // 
            resources.ApplyResources(this.AbortButton, "AbortButton");
            // 
            // FieldNameLabel
            // 
            resources.ApplyResources(this.FieldNameLabel, "FieldNameLabel");
            this.FieldNameLabel.Name = "FieldNameLabel";
            // 
            // FieldNameTextBox
            // 
            resources.ApplyResources(this.FieldNameTextBox, "FieldNameTextBox");
            this.FieldNameTextBox.Name = "FieldNameTextBox";
            this.FieldNameTextBox.TextChanged += new System.EventHandler(this.FieldNameTextBox_TextChanged);
            // 
            // FieldValueLabel
            // 
            resources.ApplyResources(this.FieldValueLabel, "FieldValueLabel");
            this.FieldValueLabel.Name = "FieldValueLabel";
            // 
            // FieldValueTextBox
            // 
            resources.ApplyResources(this.FieldValueTextBox, "FieldValueTextBox");
            this.FieldValueTextBox.Name = "FieldValueTextBox";
            this.FieldValueTextBox.TextChanged += new System.EventHandler(this.FieldValueTextBox_TextChanged);
            // 
            // WorkItemFieldEditorDialog
            // 
            resources.ApplyResources(this, "$this");
            this.Controls.Add(this.FieldNameLabel);
            this.Controls.Add(this.FieldValueTextBox);
            this.Controls.Add(this.FieldNameTextBox);
            this.Controls.Add(this.FieldValueLabel);
            this.Name = "WorkItemFieldEditorDialog";
            this.Load += new System.EventHandler(this.WorkItemFieldEditorDialog_Load);
            this.Controls.SetChildIndex(this.FieldValueLabel, 0);
            this.Controls.SetChildIndex(this.FieldNameTextBox, 0);
            this.Controls.SetChildIndex(this.FieldValueTextBox, 0);
            this.Controls.SetChildIndex(this.FieldNameLabel, 0);
            this.Controls.SetChildIndex(this.AbortButton, 0);
            this.Controls.SetChildIndex(this.SubmitButton, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label FieldNameLabel;
        private System.Windows.Forms.TextBox FieldNameTextBox;
        private System.Windows.Forms.Label FieldValueLabel;
        private System.Windows.Forms.TextBox FieldValueTextBox;
    }
}
