//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Center.Diag.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiagStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorba.Center.Diag.Core.Resources.DiagStrings", typeof(DiagStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Address.
        /// </summary>
        public static string AddUnitDialog_UnitAddress {
            get {
                return ResourceManager.GetString("AddUnitDialog_UnitAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unit.
        /// </summary>
        public static string AllUnits_AddUnit {
            get {
                return ResourceManager.GetString("AllUnits_AddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string AllUnits_Connected {
            get {
                return ResourceManager.GetString("AllUnits_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string AllUnits_Favorites {
            get {
                return ResourceManager.GetString("AllUnits_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string AllUnits_Unconnected {
            get {
                return ResourceManager.GetString("AllUnits_Unconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Properties.
        /// </summary>
        public static string AllUnits_UnitProperties {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string AllUnits_UnitProperties_CommonGroup {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_CommonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Mode.
        /// </summary>
        public static string AllUnits_UnitProperties_ConnectionMode {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_ConnectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The way icenter.diag connects to this Unit.
        /// </summary>
        public static string AllUnits_UnitProperties_ConnectionMode_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_ConnectionMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection State.
        /// </summary>
        public static string AllUnits_UnitProperties_ConnectionState {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_ConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection state of the unit.
        /// </summary>
        public static string AllUnits_UnitProperties_ConnectionState_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_ConnectionState_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AllUnits_UnitProperties_Description {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the unit, you may write your own notes here..
        /// </summary>
        public static string AllUnits_UnitProperties_Description_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_Description_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHCP Enabled.
        /// </summary>
        public static string AllUnits_UnitProperties_DhcpEnabled {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_DhcpEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the Unit is set to use DHCP to get its IP address..
        /// </summary>
        public static string AllUnits_UnitProperties_DhcpEnabled_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_DhcpEnabled_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        public static string AllUnits_UnitProperties_Gateway {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP gateway of the unit.
        /// </summary>
        public static string AllUnits_UnitProperties_Gateway_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_Gateway_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string AllUnits_UnitProperties_IPAddress {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP address of the unit.
        /// </summary>
        public static string AllUnits_UnitProperties_IPAddress_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_IPAddress_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AllUnits_UnitProperties_Name {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the unit.
        /// </summary>
        public static string AllUnits_UnitProperties_Name_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_Name_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Mask.
        /// </summary>
        public static string AllUnits_UnitProperties_NetworkMask {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_NetworkMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP network mask of the unit.
        /// </summary>
        public static string AllUnits_UnitProperties_NetworkMask_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_NetworkMask_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDCP version.
        /// </summary>
        public static string AllUnits_UnitProperties_SoftwareVersion {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UDCP software version of the unit.
        /// </summary>
        public static string AllUnits_UnitProperties_SoftwareVersion_Help {
            get {
                return ResourceManager.GetString("AllUnits_UnitProperties_SoftwareVersion_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application I/O.
        /// </summary>
        public static string AppInfoPart_ApplicationIO {
            get {
                return ResourceManager.GetString("AppInfoPart_ApplicationIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medi Management Tree.
        /// </summary>
        public static string AppInfoPart_MediManagementTree {
            get {
                return ResourceManager.GetString("AppInfoPart_MediManagementTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Log.
        /// </summary>
        public static string AppInfoPart_RemoteLog {
            get {
                return ResourceManager.GetString("AppInfoPart_RemoteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} I/O Ports.
        /// </summary>
        public static string ApplicationIoCountLabel {
            get {
                return ResourceManager.GetString("ApplicationIoCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Log Messages.
        /// </summary>
        public static string ApplicationLogCountLabel {
            get {
                return ResourceManager.GetString("ApplicationLogCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ApplicationMenu_End {
            get {
                return ResourceManager.GetString("ApplicationMenu_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ApplicationMenu_EndGestureText {
            get {
                return ResourceManager.GetString("ApplicationMenu_EndGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string ApplicationMenu_Launch {
            get {
                return ResourceManager.GetString("ApplicationMenu_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ApplicationMenu_LaunchGestureText {
            get {
                return ResourceManager.GetString("ApplicationMenu_LaunchGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch.
        /// </summary>
        public static string ApplicationMenu_Relaunch {
            get {
                return ResourceManager.GetString("ApplicationMenu_Relaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ApplicationMenu_RelaunchGestureText {
            get {
                return ResourceManager.GetString("ApplicationMenu_RelaunchGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string BusyIndicator_Downloading {
            get {
                return ResourceManager.GetString("BusyIndicator_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string BusyIndicator_Loading {
            get {
                return ResourceManager.GetString("BusyIndicator_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background System.
        /// </summary>
        public static string ConnectionMode_BackgroundSystem {
            get {
                return ResourceManager.GetString("ConnectionMode_BackgroundSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string ConnectionMode_Local {
            get {
                return ResourceManager.GetString("ConnectionMode_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string ConnectionMode_NotAvailable {
            get {
                return ResourceManager.GetString("ConnectionMode_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ConnectionState_Connected {
            get {
                return ResourceManager.GetString("ConnectionState_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string ConnectionState_Connecting {
            get {
                return ResourceManager.GetString("ConnectionState_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string ConnectionState_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionState_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use DHCP.
        /// </summary>
        public static string EditIpSettingsDialog_DhcpEnabled {
            get {
                return ResourceManager.GetString("EditIpSettingsDialog_DhcpEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        public static string EditIpSettingsDialog_GatewayAddress {
            get {
                return ResourceManager.GetString("EditIpSettingsDialog_GatewayAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Gateway Address.
        /// </summary>
        public static string EditIpSettingsDialog_GatewayAddress_Placeholder {
            get {
                return ResourceManager.GetString("EditIpSettingsDialog_GatewayAddress_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string EditIpSettingsDialog_IpAddress {
            get {
                return ResourceManager.GetString("EditIpSettingsDialog_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IP Address.
        /// </summary>
        public static string EditIpSettingsDialog_IpAddress_Placeholder {
            get {
                return ResourceManager.GetString("EditIpSettingsDialog_IpAddress_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Mask.
        /// </summary>
        public static string EditIpSettingsDialog_NetworkMask {
            get {
                return ResourceManager.GetString("EditIpSettingsDialog_NetworkMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Network Mask.
        /// </summary>
        public static string EditIpSettingsDialog_NetworkMask_Placeholder {
            get {
                return ResourceManager.GetString("EditIpSettingsDialog_NetworkMask_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string FileSystemTab_Refresh {
            get {
                return ResourceManager.GetString("FileSystemTab_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file....
        /// </summary>
        public static string FileSystemView_DownloadFile_DialogTitle {
            get {
                return ResourceManager.GetString("FileSystemView_DownloadFile_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download file &apos;{0}&apos;.{1}{2}.
        /// </summary>
        public static string FileSystemView_DownloadFile_Error {
            get {
                return ResourceManager.GetString("FileSystemView_DownloadFile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded the file to &apos;{0}&apos;.
        /// </summary>
        public static string FileSystemView_DownloadFile_Success {
            get {
                return ResourceManager.GetString("FileSystemView_DownloadFile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FileSystemViewDownloadFile {
            get {
                return ResourceManager.GetString("FileSystemViewDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileSystemViewOpenFile {
            get {
                return ResourceManager.GetString("FileSystemViewOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string IoColumnName {
            get {
                return ResourceManager.GetString("IoColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string IoColumnValue {
            get {
                return ResourceManager.GetString("IoColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each octet of an IP address should be between 0 and 255..
        /// </summary>
        public static string IPValidation_InvalidValues {
            get {
                return ResourceManager.GetString("IPValidation_InvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an IP address..
        /// </summary>
        public static string IPValidation_NoIP {
            get {
                return ResourceManager.GetString("IPValidation_NoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address should be four octets, separated by dots..
        /// </summary>
        public static string IPValidation_NotCorrectLength {
            get {
                return ResourceManager.GetString("IPValidation_NotCorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each octet of an IP address should be a number..
        /// </summary>
        public static string IPValidation_OnlyNumbers {
            get {
                return ResourceManager.GetString("IPValidation_OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT + F4.
        /// </summary>
        public static string MainMenu_ExitGestureText {
            get {
                return ResourceManager.GetString("MainMenu_ExitGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs/Outputs.
        /// </summary>
        public static string OverviewTitle_ApplicationIo {
            get {
                return ResourceManager.GetString("OverviewTitle_ApplicationIo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string OverviewTitle_MediTree {
            get {
                return ResourceManager.GetString("OverviewTitle_MediTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Log.
        /// </summary>
        public static string OverviewTitle_RemoteLog {
            get {
                return ResourceManager.GetString("OverviewTitle_RemoteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll automatically.
        /// </summary>
        public static string RemoteLog_AutoScroll {
            get {
                return ResourceManager.GetString("RemoteLog_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string RemoteLog_ClearAll {
            get {
                return ResourceManager.GetString("RemoteLog_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string RemoteLog_Enabled {
            get {
                return ResourceManager.GetString("RemoteLog_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Level:.
        /// </summary>
        public static string RemoteLog_MinLevel {
            get {
                return ResourceManager.GetString("RemoteLog_MinLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string RemoteViewer_Alt {
            get {
                return ResourceManager.GetString("RemoteViewer_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string RemoteViewer_Ctrl {
            get {
                return ResourceManager.GetString("RemoteViewer_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to screen.
        /// </summary>
        public static string RemoteViewer_FitToScreen {
            get {
                return ResourceManager.GetString("RemoteViewer_FitToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to switch to interactive mode? Others might see your actions on the remote device..
        /// </summary>
        public static string RemoteViewer_InteractiveQuery {
            get {
                return ResourceManager.GetString("RemoteViewer_InteractiveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Mode.
        /// </summary>
        public static string RemoteViewer_InteractiveQueryTitle {
            get {
                return ResourceManager.GetString("RemoteViewer_InteractiveQueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Mode.
        /// </summary>
        public static string RemoteViewer_IsInteractive {
            get {
                return ResourceManager.GetString("RemoteViewer_IsInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string RemoteViewer_Shift {
            get {
                return ResourceManager.GetString("RemoteViewer_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string RemoteViewer_Win {
            get {
                return ResourceManager.GetString("RemoteViewer_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Units.
        /// </summary>
        public static string Shell_AllUnitsTabHeader {
            get {
                return ResourceManager.GetString("Shell_AllUnitsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Mode.
        /// </summary>
        public static string Unit_ConnectionMode_Header {
            get {
                return ResourceManager.GetString("Unit_ConnectionMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection State.
        /// </summary>
        public static string Unit_ConnectionState_Header {
            get {
                return ResourceManager.GetString("Unit_ConnectionState_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Unit_Description_Header {
            get {
                return ResourceManager.GetString("Unit_Description_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHCP.
        /// </summary>
        public static string Unit_Dhcp_Header {
            get {
                return ResourceManager.GetString("Unit_Dhcp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Address.
        /// </summary>
        public static string Unit_GatewayAddress_Header {
            get {
                return ResourceManager.GetString("Unit_GatewayAddress_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-Address.
        /// </summary>
        public static string Unit_IpAddress_Header {
            get {
                return ResourceManager.GetString("Unit_IpAddress_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Unit_Name_Header {
            get {
                return ResourceManager.GetString("Unit_Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Mask.
        /// </summary>
        public static string Unit_NetworkMask_Header {
            get {
                return ResourceManager.GetString("Unit_NetworkMask_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDCP Version.
        /// </summary>
        public static string Unit_SoftwareVersion_Header {
            get {
                return ResourceManager.GetString("Unit_SoftwareVersion_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit {0} on {1}?.
        /// </summary>
        public static string UnitAction_ReallyEndApplicationMessage {
            get {
                return ResourceManager.GetString("UnitAction_ReallyEndApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reboot {0}?.
        /// </summary>
        public static string UnitAction_ReallyRebootMessage {
            get {
                return ResourceManager.GetString("UnitAction_ReallyRebootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to relaunch {0} on {1}?.
        /// </summary>
        public static string UnitAction_ReallyRelaunchApplicationMessage {
            get {
                return ResourceManager.GetString("UnitAction_ReallyRelaunchApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string UnitMenu_Add {
            get {
                return ResourceManager.GetString("UnitMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL + SHIFT + A.
        /// </summary>
        public static string UnitMenu_AddGestureText {
            get {
                return ResourceManager.GetString("UnitMenu_AddGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announce.
        /// </summary>
        public static string UnitMenu_Announce {
            get {
                return ResourceManager.GetString("UnitMenu_Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnitMenu_AnnounceGestureText {
            get {
                return ResourceManager.GetString("UnitMenu_AnnounceGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string UnitMenu_Connect {
            get {
                return ResourceManager.GetString("UnitMenu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnitMenu_ConnectGestureText {
            get {
                return ResourceManager.GetString("UnitMenu_ConnectGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string UnitMenu_Disconnect {
            get {
                return ResourceManager.GetString("UnitMenu_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnitMenu_DisconnectGestureText {
            get {
                return ResourceManager.GetString("UnitMenu_DisconnectGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit IP Settings.
        /// </summary>
        public static string UnitMenu_EditIPSettings {
            get {
                return ResourceManager.GetString("UnitMenu_EditIPSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnitMenu_EditIPSettingsGestureText {
            get {
                return ResourceManager.GetString("UnitMenu_EditIPSettingsGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string UnitMenu_Reboot {
            get {
                return ResourceManager.GetString("UnitMenu_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnitMenu_RebootGestureText {
            get {
                return ResourceManager.GetString("UnitMenu_RebootGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string UnitMenu_Remove {
            get {
                return ResourceManager.GetString("UnitMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnitMenu_RemoveGestureText {
            get {
                return ResourceManager.GetString("UnitMenu_RemoveGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announce.
        /// </summary>
        public static string UnitTab_AnnounceUnit {
            get {
                return ResourceManager.GetString("UnitTab_AnnounceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string UnitTab_BusyConnecting {
            get {
                return ResourceManager.GetString("UnitTab_BusyConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string UnitTab_DisconnectUnit {
            get {
                return ResourceManager.GetString("UnitTab_DisconnectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string UnitTab_RestartUnit {
            get {
                return ResourceManager.GetString("UnitTab_RestartUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        public static string UnitTabSection_FileSystemInfo {
            get {
                return ResourceManager.GetString("UnitTabSection_FileSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Viewer.
        /// </summary>
        public static string UnitTabSection_RemoteViewer {
            get {
                return ResourceManager.GetString("UnitTabSection_RemoteViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        public static string UnitTabSection_SystemInfo {
            get {
                return ResourceManager.GetString("UnitTabSection_SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: {0}{3}CPU usage: {1}{3}RAM usage: {2} bytes.
        /// </summary>
        public static string UnitTabSection_Tooltip_Format {
            get {
                return ResourceManager.GetString("UnitTabSection_Tooltip_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit I/O.
        /// </summary>
        public static string UnitTabSection_UnitIoInfo {
            get {
                return ResourceManager.GetString("UnitTabSection_UnitIoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ViewMenu_Refresh {
            get {
                return ResourceManager.GetString("ViewMenu_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ViewMenu_RefreshGestureText {
            get {
                return ResourceManager.GetString("ViewMenu_RefreshGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ViewMenu_Reset {
            get {
                return ResourceManager.GetString("ViewMenu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ViewMenu_ResetGestureText {
            get {
                return ResourceManager.GetString("ViewMenu_ResetGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tile Overview.
        /// </summary>
        public static string ViewMenu_ShowTileView {
            get {
                return ResourceManager.GetString("ViewMenu_ShowTileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Window_Application {
            get {
                return ResourceManager.GetString("Window_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Window_File {
            get {
                return ResourceManager.GetString("Window_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Window_Unit {
            get {
                return ResourceManager.GetString("Window_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Window_View {
            get {
                return ResourceManager.GetString("Window_View", resourceCulture);
            }
        }
    }
}
