//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Center.Common.Wpf.Framework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrameworkStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorba.Center.Common.Wpf.Framework.FrameworkStrings", typeof(FrameworkStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutScreen_About {
            get {
                return ResourceManager.GetString("AboutScreen_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone +41 71 955 74 74.
        /// </summary>
        public static string AboutScreen_Phone {
            get {
                return ResourceManager.GetString("AboutScreen_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string AboutScreen_Switzerland {
            get {
                return ResourceManager.GetString("AboutScreen_Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log directory.
        /// </summary>
        public static string Application_UnhandledExceptionHyperlink {
            get {
                return ResourceManager.GetString("Application_UnhandledExceptionHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred which will terminate the application.
        /// </summary>
        public static string Application_UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("Application_UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string Application_UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("Application_UnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MultiSelectionEditor_AllItems {
            get {
                return ResourceManager.GetString("MultiSelectionEditor_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string OptionsDialog_GeneralTitle {
            get {
                return ResourceManager.GetString("OptionsDialog_GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options.
        /// </summary>
        public static string OptionsDialog_GeneralTooltip {
            get {
                return ResourceManager.GetString("OptionsDialog_GeneralTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsDialog_LanguageLabel {
            get {
                return ResourceManager.GetString("OptionsDialog_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the language used in the application..
        /// </summary>
        public static string OptionsDialog_LanguageLabelTooltip {
            get {
                return ResourceManager.GetString("OptionsDialog_LanguageLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the language takes effect after relogin or restart of the application..
        /// </summary>
        public static string OptionsDialog_LanguageRestartInformation {
            get {
                return ResourceManager.GetString("OptionsDialog_LanguageRestartInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string OptionsDialog_MenuItem {
            get {
                return ResourceManager.GetString("OptionsDialog_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsDialog_Title {
            get {
                return ResourceManager.GetString("OptionsDialog_Title", resourceCulture);
            }
        }
    }
}
