// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class AddMediaConfiguration : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.MediaConfigurations",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        CreatedOn = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        LastModifiedOn = c.DateTime(precision: 7, storeType: "datetime2"),
                        Version = c.Int(nullable: false),
                        Document_Id = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Documents", t => t.Document_Id, cascadeDelete: true)
                .Index(t => t.Document_Id);

            AddColumn("dbo.UpdateGroups", "MediaConfiguration_Id", c => c.Int());
            CreateIndex("dbo.UpdateGroups", "MediaConfiguration_Id");
            AddForeignKey("dbo.UpdateGroups", "MediaConfiguration_Id", "dbo.MediaConfigurations", "Id");
            this.SetDefaultValueForVersions();
        }

        public override void Down()
        {
            DropForeignKey("dbo.UpdateGroups", "MediaConfiguration_Id", "dbo.MediaConfigurations");
            DropForeignKey("dbo.MediaConfigurations", "Document_Id", "dbo.Documents");
            DropIndex("dbo.MediaConfigurations", new[] { "Document_Id" });
            DropIndex("dbo.UpdateGroups", new[] { "MediaConfiguration_Id" });
            DropColumn("dbo.UpdateGroups", "MediaConfiguration_Id");
            DropTable("dbo.MediaConfigurations");
        }
    }
}
