// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    // ReSharper disable once InconsistentNaming
    public partial class LogEntry_SystemConfig_UpdateFixes : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.UpdateParts", "UpdateCommand_Id", "dbo.UpdateCommands");
            DropIndex("dbo.UpdateParts", new[] { "UpdateCommand_Id" });
            CreateTable(
                "dbo.LogEntries",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Application = c.String(nullable: false),
                        Timestamp = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        Level = c.Int(nullable: false),
                        Logger = c.String(nullable: false),
                        Message = c.String(nullable: false),
                        AdditionalData = c.String(),
                        Unit_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Units", t => t.Unit_Id)
                .Index(t => t.Unit_Id);
            
            CreateTable(
                "dbo.SystemConfigs",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        SystemId = c.Guid(nullable: false),
                        SettingsXml = c.String(),
                        SettingsXmlType = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            DropColumn("dbo.UpdateParts", "UpdateCommand_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.UpdateParts", "UpdateCommand_Id", c => c.Int(nullable: false));
            DropForeignKey("dbo.LogEntries", "Unit_Id", "dbo.Units");
            DropIndex("dbo.LogEntries", new[] { "Unit_Id" });
            DropTable("dbo.SystemConfigs");
            DropTable("dbo.LogEntries");
            CreateIndex("dbo.UpdateParts", "UpdateCommand_Id");
            AddForeignKey("dbo.UpdateParts", "UpdateCommand_Id", "dbo.UpdateCommands", "Id");
        }
    }
}
