// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class DataScopesAndNullableTenantOnAssociation : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.AssociationTenantUserUserRoles", "Tenant_Id", "dbo.Tenants");
            DropIndex("dbo.AssociationTenantUserUserRoles", new[] { "Tenant_Id" });
            AlterColumn("dbo.AssociationTenantUserUserRoles", "Tenant_Id", c => c.Int());
            CreateIndex("dbo.AssociationTenantUserUserRoles", "Tenant_Id");
            AddForeignKey("dbo.AssociationTenantUserUserRoles", "Tenant_Id", "dbo.Tenants", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.AssociationTenantUserUserRoles", "Tenant_Id", "dbo.Tenants");
            DropIndex("dbo.AssociationTenantUserUserRoles", new[] { "Tenant_Id" });
            AlterColumn("dbo.AssociationTenantUserUserRoles", "Tenant_Id", c => c.Int(nullable: false));
            CreateIndex("dbo.AssociationTenantUserUserRoles", "Tenant_Id");
            AddForeignKey("dbo.AssociationTenantUserUserRoles", "Tenant_Id", "dbo.Tenants", "Id", cascadeDelete: true);
        }
    }
}