// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RenamedUserDefinedPropertiesKeyToName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamedUserDefinedPropertiesKeyToName));
        
        string IMigrationMetadata.Id
        {
            get { return "201410131250476_RenamedUserDefinedPropertiesKeyToName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
