// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;

    // ReSharper disable once InconsistentNaming
    public partial class UpdateCommand_WasTransferred : DbMigration
    {
        public override void Up()
        {
            this.AddColumn("dbo.UpdateCommands", "WasTransferred", c => c.Boolean(nullable: false));
        }

        public override void Down()
        {
            this.DropColumn("dbo.UpdateCommands", "WasTransferred");
        }
    }
}
