// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UserDefinedProperties : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.UnitUserDefinedProperties",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        CreatedOn = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        LastModifiedOn = c.DateTime(precision: 7, storeType: "datetime2"),
                        Version = c.Int(nullable: false),
                        Value = c.String(),
                        PropertyDefinition_Id = c.Int(nullable: false),
                        Unit_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.UserDefinedProperties", t => t.PropertyDefinition_Id, cascadeDelete: true)
                .ForeignKey("dbo.Units", t => t.Unit_Id)
                .Index(t => t.PropertyDefinition_Id)
                .Index(t => t.Unit_Id);
            
            CreateTable(
                "dbo.UserDefinedProperties",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        CreatedOn = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        LastModifiedOn = c.DateTime(precision: 7, storeType: "datetime2"),
                        Version = c.Int(nullable: false),
                        OwnerEntity = c.Int(nullable: false),
                        Key = c.String(maxLength: 100),
                        Tenant_Id = c.Int(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Tenants", t => t.Tenant_Id)
                .Index(t => t.Key, unique: true)
                .Index(t => t.Tenant_Id);
            this.SetDefaultValueForVersions();
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UnitUserDefinedProperties", "Unit_Id", "dbo.Units");
            DropForeignKey("dbo.UnitUserDefinedProperties", "PropertyDefinition_Id", "dbo.UserDefinedProperties");
            DropForeignKey("dbo.UserDefinedProperties", "Tenant_Id", "dbo.Tenants");
            DropIndex("dbo.UserDefinedProperties", new[] { "Tenant_Id" });
            DropIndex("dbo.UserDefinedProperties", new[] { "Key" });
            DropIndex("dbo.UnitUserDefinedProperties", new[] { "Unit_Id" });
            DropIndex("dbo.UnitUserDefinedProperties", new[] { "PropertyDefinition_Id" });
            DropTable("dbo.UserDefinedProperties");
            DropTable("dbo.UnitUserDefinedProperties");
        }
    }
}
