// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class SystemConfigChangeTracking : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.SystemConfigs", "CreatedOn", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("dbo.SystemConfigs", "LastModifiedOn", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.SystemConfigs", "Version", c => c.Int(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.SystemConfigs", "Version");
            DropColumn("dbo.SystemConfigs", "LastModifiedOn");
            DropColumn("dbo.SystemConfigs", "CreatedOn");
        }
    }
}
