// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class XmlDataRemoveColumns : DbMigration
    {
        public override void Up()
        {
            DropColumn("dbo.DocumentVersions", "ContentXml");
            DropColumn("dbo.DocumentVersions", "ContentXmlType");
            DropColumn("dbo.ProductTypes", "HardwareDescriptorXml");
            DropColumn("dbo.ProductTypes", "HardwareDescriptorXmlType");
            DropColumn("dbo.UpdateCommands", "CommandXml");
            DropColumn("dbo.UpdateCommands", "CommandXmlType");
            DropColumn("dbo.UpdateFeedbacks", "FeedbackXml");
            DropColumn("dbo.UpdateFeedbacks", "FeedbackXmlType");
            DropColumn("dbo.UpdateParts", "StructureXml");
            DropColumn("dbo.UpdateParts", "StructureXmlType");
            DropColumn("dbo.PackageVersions", "StructureXml");
            DropColumn("dbo.PackageVersions", "StructureXmlType");
            DropColumn("dbo.SystemConfigs", "SettingsXml");
            DropColumn("dbo.SystemConfigs", "SettingsXmlType");
        }
        
        public override void Down()
        {
            AddColumn("dbo.SystemConfigs", "SettingsXmlType", c => c.String());
            AddColumn("dbo.SystemConfigs", "SettingsXml", c => c.String());
            AddColumn("dbo.PackageVersions", "StructureXmlType", c => c.String());
            AddColumn("dbo.PackageVersions", "StructureXml", c => c.String());
            AddColumn("dbo.UpdateParts", "StructureXmlType", c => c.String());
            AddColumn("dbo.UpdateParts", "StructureXml", c => c.String());
            AddColumn("dbo.UpdateFeedbacks", "FeedbackXmlType", c => c.String());
            AddColumn("dbo.UpdateFeedbacks", "FeedbackXml", c => c.String());
            AddColumn("dbo.UpdateCommands", "CommandXmlType", c => c.String());
            AddColumn("dbo.UpdateCommands", "CommandXml", c => c.String());
            AddColumn("dbo.ProductTypes", "HardwareDescriptorXmlType", c => c.String());
            AddColumn("dbo.ProductTypes", "HardwareDescriptorXml", c => c.String());
            AddColumn("dbo.DocumentVersions", "ContentXmlType", c => c.String());
            AddColumn("dbo.DocumentVersions", "ContentXml", c => c.String());
        }
    }
}
