// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class UpdatePart_Add_InstallInstructions : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.UpdateParts", "InstallInstructions_Id", c => c.Int());
            CreateIndex("dbo.UpdateParts", "InstallInstructions_Id");
            AddForeignKey("dbo.UpdateParts", "InstallInstructions_Id", "dbo.XmlDatas", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UpdateParts", "InstallInstructions_Id", "dbo.XmlDatas");
            DropIndex("dbo.UpdateParts", new[] { "InstallInstructions_Id" });
            DropColumn("dbo.UpdateParts", "InstallInstructions_Id");
        }
    }
}
