// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class RemoveAllCascadeDelete : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.AssociationTenantUserUserRoles", "UserRole_Id", "dbo.UserRoles");
            DropForeignKey("dbo.UpdateParts", "UpdateGroup_Id", "dbo.UpdateGroups");
            DropForeignKey("dbo.MediaConfigurations", "Document_Id", "dbo.Documents");
            DropForeignKey("dbo.Documents", "Tenant_Id", "dbo.Tenants");
            DropForeignKey("dbo.DocumentVersions", "Document_Id", "dbo.Documents");
            DropForeignKey("dbo.UnitConfigurations", "Document_Id", "dbo.Documents");
            DropForeignKey("dbo.UnitConfigurations", "ProductType_Id", "dbo.ProductTypes");
            DropForeignKey("dbo.Units", "ProductType_Id", "dbo.ProductTypes");
            DropForeignKey("dbo.Units", "Tenant_Id", "dbo.Tenants");
            DropForeignKey("dbo.UpdateCommands", "Unit_Id", "dbo.Units");
            DropForeignKey("dbo.UpdateFeedbacks", "UpdateCommand_Id", "dbo.UpdateCommands");
            DropForeignKey("dbo.PackageVersions", "Package_Id", "dbo.Packages");
            AddForeignKey("dbo.AssociationTenantUserUserRoles", "UserRole_Id", "dbo.UserRoles", "Id");
            AddForeignKey("dbo.UpdateParts", "UpdateGroup_Id", "dbo.UpdateGroups", "Id");
            AddForeignKey("dbo.MediaConfigurations", "Document_Id", "dbo.Documents", "Id");
            AddForeignKey("dbo.Documents", "Tenant_Id", "dbo.Tenants", "Id");
            AddForeignKey("dbo.DocumentVersions", "Document_Id", "dbo.Documents", "Id");
            AddForeignKey("dbo.UnitConfigurations", "Document_Id", "dbo.Documents", "Id");
            AddForeignKey("dbo.UnitConfigurations", "ProductType_Id", "dbo.ProductTypes", "Id");
            AddForeignKey("dbo.Units", "ProductType_Id", "dbo.ProductTypes", "Id");
            AddForeignKey("dbo.Units", "Tenant_Id", "dbo.Tenants", "Id");
            AddForeignKey("dbo.UpdateCommands", "Unit_Id", "dbo.Units", "Id");
            AddForeignKey("dbo.UpdateFeedbacks", "UpdateCommand_Id", "dbo.UpdateCommands", "Id");
            AddForeignKey("dbo.PackageVersions", "Package_Id", "dbo.Packages", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.PackageVersions", "Package_Id", "dbo.Packages");
            DropForeignKey("dbo.UpdateFeedbacks", "UpdateCommand_Id", "dbo.UpdateCommands");
            DropForeignKey("dbo.UpdateCommands", "Unit_Id", "dbo.Units");
            DropForeignKey("dbo.Units", "Tenant_Id", "dbo.Tenants");
            DropForeignKey("dbo.Units", "ProductType_Id", "dbo.ProductTypes");
            DropForeignKey("dbo.UnitConfigurations", "ProductType_Id", "dbo.ProductTypes");
            DropForeignKey("dbo.UnitConfigurations", "Document_Id", "dbo.Documents");
            DropForeignKey("dbo.DocumentVersions", "Document_Id", "dbo.Documents");
            DropForeignKey("dbo.Documents", "Tenant_Id", "dbo.Tenants");
            DropForeignKey("dbo.MediaConfigurations", "Document_Id", "dbo.Documents");
            DropForeignKey("dbo.UpdateParts", "UpdateGroup_Id", "dbo.UpdateGroups");
            DropForeignKey("dbo.AssociationTenantUserUserRoles", "UserRole_Id", "dbo.UserRoles");
            AddForeignKey("dbo.PackageVersions", "Package_Id", "dbo.Packages", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UpdateFeedbacks", "UpdateCommand_Id", "dbo.UpdateCommands", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UpdateCommands", "Unit_Id", "dbo.Units", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Units", "Tenant_Id", "dbo.Tenants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Units", "ProductType_Id", "dbo.ProductTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UnitConfigurations", "ProductType_Id", "dbo.ProductTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UnitConfigurations", "Document_Id", "dbo.Documents", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DocumentVersions", "Document_Id", "dbo.Documents", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Documents", "Tenant_Id", "dbo.Tenants", "Id", cascadeDelete: true);
            AddForeignKey("dbo.MediaConfigurations", "Document_Id", "dbo.Documents", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UpdateParts", "UpdateGroup_Id", "dbo.UpdateGroups", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AssociationTenantUserUserRoles", "UserRole_Id", "dbo.UserRoles", "Id", cascadeDelete: true);
        }
    }
}
