// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class XmlDataAddSeparateTable : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.XmlDatas",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Xml = c.String(),
                        Type = c.String(),
                    })
                .PrimaryKey(t => t.Id);
            
            AddColumn("dbo.DocumentVersions", "Content_Id", c => c.Int());
            AddColumn("dbo.ProductTypes", "HardwareDescriptor_Id", c => c.Int());
            AddColumn("dbo.UpdateCommands", "Command_Id", c => c.Int());
            AddColumn("dbo.UpdateFeedbacks", "Feedback_Id", c => c.Int());
            AddColumn("dbo.UpdateParts", "Structure_Id", c => c.Int());
            AddColumn("dbo.PackageVersions", "Structure_Id", c => c.Int());
            AddColumn("dbo.SystemConfigs", "Settings_Id", c => c.Int());
            CreateIndex("dbo.DocumentVersions", "Content_Id");
            CreateIndex("dbo.ProductTypes", "HardwareDescriptor_Id");
            CreateIndex("dbo.UpdateCommands", "Command_Id");
            CreateIndex("dbo.UpdateFeedbacks", "Feedback_Id");
            CreateIndex("dbo.UpdateParts", "Structure_Id");
            CreateIndex("dbo.PackageVersions", "Structure_Id");
            CreateIndex("dbo.SystemConfigs", "Settings_Id");
            AddForeignKey("dbo.DocumentVersions", "Content_Id", "dbo.XmlDatas", "Id");
            AddForeignKey("dbo.ProductTypes", "HardwareDescriptor_Id", "dbo.XmlDatas", "Id");
            AddForeignKey("dbo.UpdateCommands", "Command_Id", "dbo.XmlDatas", "Id");
            AddForeignKey("dbo.UpdateFeedbacks", "Feedback_Id", "dbo.XmlDatas", "Id");
            AddForeignKey("dbo.UpdateParts", "Structure_Id", "dbo.XmlDatas", "Id");
            AddForeignKey("dbo.PackageVersions", "Structure_Id", "dbo.XmlDatas", "Id");
            AddForeignKey("dbo.SystemConfigs", "Settings_Id", "dbo.XmlDatas", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.SystemConfigs", "Settings_Id", "dbo.XmlDatas");
            DropForeignKey("dbo.PackageVersions", "Structure_Id", "dbo.XmlDatas");
            DropForeignKey("dbo.UpdateParts", "Structure_Id", "dbo.XmlDatas");
            DropForeignKey("dbo.UpdateFeedbacks", "Feedback_Id", "dbo.XmlDatas");
            DropForeignKey("dbo.UpdateCommands", "Command_Id", "dbo.XmlDatas");
            DropForeignKey("dbo.ProductTypes", "HardwareDescriptor_Id", "dbo.XmlDatas");
            DropForeignKey("dbo.DocumentVersions", "Content_Id", "dbo.XmlDatas");
            DropIndex("dbo.SystemConfigs", new[] { "Settings_Id" });
            DropIndex("dbo.PackageVersions", new[] { "Structure_Id" });
            DropIndex("dbo.UpdateParts", new[] { "Structure_Id" });
            DropIndex("dbo.UpdateFeedbacks", new[] { "Feedback_Id" });
            DropIndex("dbo.UpdateCommands", new[] { "Command_Id" });
            DropIndex("dbo.ProductTypes", new[] { "HardwareDescriptor_Id" });
            DropIndex("dbo.DocumentVersions", new[] { "Content_Id" });
            DropColumn("dbo.SystemConfigs", "Settings_Id");
            DropColumn("dbo.PackageVersions", "Structure_Id");
            DropColumn("dbo.UpdateParts", "Structure_Id");
            DropColumn("dbo.UpdateFeedbacks", "Feedback_Id");
            DropColumn("dbo.UpdateCommands", "Command_Id");
            DropColumn("dbo.ProductTypes", "HardwareDescriptor_Id");
            DropColumn("dbo.DocumentVersions", "Content_Id");
            DropTable("dbo.XmlDatas");
        }
    }
}
