// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class AddUnitIsConnected : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Units", "IsConnected", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Units", "IsConnected");
        }
    }
}
