// <auto-generated />
namespace Gorba.Center.BackgroundSystem.Data.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class UdpCleanup : DbMigration
    {
        public override void Up()
        {
            DropColumn("dbo.UserUserDefinedProperties", "CreatedOn");
            DropColumn("dbo.UserUserDefinedProperties", "LastModifiedOn");
            DropColumn("dbo.UserUserDefinedProperties", "Version");
            DropColumn("dbo.UnitUserDefinedProperties", "CreatedOn");
            DropColumn("dbo.UnitUserDefinedProperties", "LastModifiedOn");
            DropColumn("dbo.UnitUserDefinedProperties", "Version");
            DropColumn("dbo.UpdateGroupUserDefinedProperties", "CreatedOn");
            DropColumn("dbo.UpdateGroupUserDefinedProperties", "LastModifiedOn");
            DropColumn("dbo.UpdateGroupUserDefinedProperties", "Version");
            DropColumn("dbo.TenantUserDefinedProperties", "CreatedOn");
            DropColumn("dbo.TenantUserDefinedProperties", "LastModifiedOn");
            DropColumn("dbo.TenantUserDefinedProperties", "Version");
            DropColumn("dbo.UserRoleUserDefinedProperties", "CreatedOn");
            DropColumn("dbo.UserRoleUserDefinedProperties", "LastModifiedOn");
            DropColumn("dbo.UserRoleUserDefinedProperties", "Version");
        }
        
        public override void Down()
        {
            AddColumn("dbo.UserRoleUserDefinedProperties", "Version", c => c.Int(nullable: false));
            AddColumn("dbo.UserRoleUserDefinedProperties", "LastModifiedOn", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.UserRoleUserDefinedProperties", "CreatedOn", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("dbo.TenantUserDefinedProperties", "Version", c => c.Int(nullable: false));
            AddColumn("dbo.TenantUserDefinedProperties", "LastModifiedOn", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.TenantUserDefinedProperties", "CreatedOn", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("dbo.UpdateGroupUserDefinedProperties", "Version", c => c.Int(nullable: false));
            AddColumn("dbo.UpdateGroupUserDefinedProperties", "LastModifiedOn", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.UpdateGroupUserDefinedProperties", "CreatedOn", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("dbo.UnitUserDefinedProperties", "Version", c => c.Int(nullable: false));
            AddColumn("dbo.UnitUserDefinedProperties", "LastModifiedOn", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.UnitUserDefinedProperties", "CreatedOn", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("dbo.UserUserDefinedProperties", "Version", c => c.Int(nullable: false));
            AddColumn("dbo.UserUserDefinedProperties", "LastModifiedOn", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.UserUserDefinedProperties", "CreatedOn", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
        }
    }
}
