//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows exclusion based on the absolute or partial path to a file being checked in..
        /// </summary>
        internal static string DirectoryPolicyExclusionDesc {
            get {
                return ResourceManager.GetString("DirectoryPolicyExclusionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path.
        /// </summary>
        internal static string DirectoryPolicyExclusionName {
            get {
                return ResourceManager.GetString("DirectoryPolicyExclusionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows exclusion based on the name of a file being checked in..
        /// </summary>
        internal static string FilePolicyExclusionDesc {
            get {
                return ResourceManager.GetString("FilePolicyExclusionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FilePolicyExclusionName {
            get {
                return ResourceManager.GetString("FilePolicyExclusionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        internal static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop Settings ({0};{1})|{0};{1}|All Files (*.*)|*.*.
        /// </summary>
        internal static string Filter_StyleCopSettings {
            get {
                return ResourceManager.GetString("Filter_StyleCopSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while exporting the StyleCop settings.
        ///
        ///        ///Message: &apos;{0}&apos;.
        /// </summary>
        internal static string Message_ErrorOccurredWhileExportingSettings {
            get {
                return ResourceManager.GetString("Message_ErrorOccurredWhileExportingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while importing the StyleCop settings.
        ///
        ///        ///Message: &apos;{0}&apos;.
        /// </summary>
        internal static string Message_ErrorOccurredWhileImportingSettings {
            get {
                return ResourceManager.GetString("Message_ErrorOccurredWhileImportingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to import existing settings?.
        /// </summary>
        internal static string Message_ImportExistingSettings {
            get {
                return ResourceManager.GetString("Message_ImportExistingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred within the &apos;{0}&apos; policy..
        /// </summary>
        internal static string Message_InternalErrorOccurred {
            get {
                return ResourceManager.GetString("Message_InternalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work item id could not be parsed correctly, please check the value and try again..
        /// </summary>
        internal static string Message_InvalidWorkItemId {
            get {
                return ResourceManager.GetString("Message_InvalidWorkItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available exclusion types have been added to the policy. Please edit an existing policy exclusion type..
        /// </summary>
        internal static string Message_NoAdditionalExclusionTypes {
            get {
                return ResourceManager.GetString("Message_NoAdditionalExclusionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified any change types that should be evaluated, which disables this policy. Do you wish to continue?.
        /// </summary>
        internal static string Message_NoChangeTypesWarning {
            get {
                return ResourceManager.GetString("Message_NoChangeTypesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires any code files being checked in must pass the project code formatting guidelines..
        /// </summary>
        internal static string Message_PolicyDescription {
            get {
                return ResourceManager.GetString("Message_PolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleCop Policy.
        /// </summary>
        internal static string Message_PolicyType {
            get {
                return ResourceManager.GetString("Message_PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This policy prevents check-ins that do not pass the StyleCop formatting guidelines..
        /// </summary>
        internal static string Message_PolicyTypeDescription {
            get {
                return ResourceManager.GetString("Message_PolicyTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more StyleCop violations have been found in &apos;{0}&apos;..
        /// </summary>
        internal static string Message_SourceViolationsFound {
            get {
                return ResourceManager.GetString("Message_SourceViolationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exclusion.
        /// </summary>
        internal static string Text_AddExclusion {
            get {
                return ResourceManager.GetString("Text_AddExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one....
        /// </summary>
        internal static string Text_ChooseOne {
            get {
                return ResourceManager.GetString("Text_ChooseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exclusion.
        /// </summary>
        internal static string Text_EditExclusion {
            get {
                return ResourceManager.GetString("Text_EditExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export StyleCop Settings.
        /// </summary>
        internal static string Text_ExportStyleCopSettingsTitle {
            get {
                return ResourceManager.GetString("Text_ExportStyleCopSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import StyleCop Settings.
        /// </summary>
        internal static string Text_ImportStyleCopSettingsTitle {
            get {
                return ResourceManager.GetString("Text_ImportStyleCopSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Text_TaskCategoryError {
            get {
                return ResourceManager.GetString("Text_TaskCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Text_TaskCategoryMessage {
            get {
                return ResourceManager.GetString("Text_TaskCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Text_TaskCategoryNone {
            get {
                return ResourceManager.GetString("Text_TaskCategoryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Text_TaskCategoryWarning {
            get {
                return ResourceManager.GetString("Text_TaskCategoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows exclusion based on a field/value pair from an associated work item during the check-in..
        /// </summary>
        internal static string WorkItemFieldExclusionDesc {
            get {
                return ResourceManager.GetString("WorkItemFieldExclusionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item field.
        /// </summary>
        internal static string WorkItemFieldExclusionName {
            get {
                return ResourceManager.GetString("WorkItemFieldExclusionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0}   Value: {1}.
        /// </summary>
        internal static string WorkItemFieldExclusionValueDesc {
            get {
                return ResourceManager.GetString("WorkItemFieldExclusionValueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows exclusion based on work item ids selected during the check-in..
        /// </summary>
        internal static string WorkItemIdExclusionDesc {
            get {
                return ResourceManager.GetString("WorkItemIdExclusionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item identifier.
        /// </summary>
        internal static string WorkItemIdExclusionName {
            get {
                return ResourceManager.GetString("WorkItemIdExclusionName", resourceCulture);
            }
        }
    }
}
