// <auto-generated />
namespace Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Forms
{
    partial class AddExclusionDialog
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddExclusionDialog));
            this.ExclusionTypeComboBox = new System.Windows.Forms.ComboBox();
            this.ExclusionTypeLabel = new System.Windows.Forms.Label();
            this.DescriptionGroupBox = new System.Windows.Forms.GroupBox();
            this.DescriptionLabel = new System.Windows.Forms.Label();
            this.DescriptionGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // SubmitButton
            // 
            resources.ApplyResources(this.SubmitButton, "SubmitButton");
            // 
            // AbortButton
            // 
            resources.ApplyResources(this.AbortButton, "AbortButton");
            // 
            // ExclusionTypeComboBox
            // 
            this.ExclusionTypeComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.ExclusionTypeComboBox.FormattingEnabled = true;
            resources.ApplyResources(this.ExclusionTypeComboBox, "ExclusionTypeComboBox");
            this.ExclusionTypeComboBox.Name = "ExclusionTypeComboBox";
            this.ExclusionTypeComboBox.Sorted = true;
            this.ExclusionTypeComboBox.SelectedIndexChanged += new System.EventHandler(this.ExclusionTypeComboBox_SelectedIndexChanged);
            // 
            // ExclusionTypeLabel
            // 
            resources.ApplyResources(this.ExclusionTypeLabel, "ExclusionTypeLabel");
            this.ExclusionTypeLabel.Name = "ExclusionTypeLabel";
            // 
            // DescriptionGroupBox
            // 
            this.DescriptionGroupBox.Controls.Add(this.DescriptionLabel);
            resources.ApplyResources(this.DescriptionGroupBox, "DescriptionGroupBox");
            this.DescriptionGroupBox.Name = "DescriptionGroupBox";
            this.DescriptionGroupBox.TabStop = false;
            // 
            // DescriptionLabel
            // 
            resources.ApplyResources(this.DescriptionLabel, "DescriptionLabel");
            this.DescriptionLabel.Name = "DescriptionLabel";
            // 
            // AddExclusionDialog
            // 
            resources.ApplyResources(this, "$this");
            this.Controls.Add(this.ExclusionTypeComboBox);
            this.Controls.Add(this.ExclusionTypeLabel);
            this.Controls.Add(this.DescriptionGroupBox);
            this.Name = "AddExclusionDialog";
            this.Load += new System.EventHandler(this.AddExclusionDialog_Load);
            this.Controls.SetChildIndex(this.DescriptionGroupBox, 0);
            this.Controls.SetChildIndex(this.ExclusionTypeLabel, 0);
            this.Controls.SetChildIndex(this.ExclusionTypeComboBox, 0);
            this.Controls.SetChildIndex(this.AbortButton, 0);
            this.Controls.SetChildIndex(this.SubmitButton, 0);
            this.DescriptionGroupBox.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ComboBox ExclusionTypeComboBox;
        private System.Windows.Forms.Label ExclusionTypeLabel;
        private System.Windows.Forms.GroupBox DescriptionGroupBox;
        private System.Windows.Forms.Label DescriptionLabel;
    }
}
