// <auto-generated />
namespace Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Forms
{
    partial class DisplayViolationsDialog
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DisplayViolationsDialog));
            this.CloseButton = new System.Windows.Forms.Button();
            this.MainStatusStrip = new System.Windows.Forms.StatusStrip();
            this.ExceptionsLabel = new System.Windows.Forms.Label();
            this.ViolationsListView = new System.Windows.Forms.ListView();
            this.RuleColumnHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.MessageColumnHeader = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.SuspendLayout();
            // 
            // CloseButton
            // 
            resources.ApplyResources(this.CloseButton, "CloseButton");
            this.CloseButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.CloseButton.Name = "CloseButton";
            this.CloseButton.UseVisualStyleBackColor = true;
            this.CloseButton.Click += new System.EventHandler(this.CloseButton_Click);
            // 
            // MainStatusStrip
            // 
            resources.ApplyResources(this.MainStatusStrip, "MainStatusStrip");
            this.MainStatusStrip.Name = "MainStatusStrip";
            // 
            // ExceptionsLabel
            // 
            resources.ApplyResources(this.ExceptionsLabel, "ExceptionsLabel");
            this.ExceptionsLabel.Name = "ExceptionsLabel";
            // 
            // ViolationsListView
            // 
            resources.ApplyResources(this.ViolationsListView, "ViolationsListView");
            this.ViolationsListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.RuleColumnHeader,
            this.MessageColumnHeader});
            this.ViolationsListView.FullRowSelect = true;
            this.ViolationsListView.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
            this.ViolationsListView.MultiSelect = false;
            this.ViolationsListView.Name = "ViolationsListView";
            this.ViolationsListView.UseCompatibleStateImageBehavior = false;
            this.ViolationsListView.View = System.Windows.Forms.View.Details;
            // 
            // RuleColumnHeader
            // 
            resources.ApplyResources(this.RuleColumnHeader, "RuleColumnHeader");
            // 
            // MessageColumnHeader
            // 
            resources.ApplyResources(this.MessageColumnHeader, "MessageColumnHeader");
            // 
            // DisplayViolationsDialog
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.CloseButton;
            this.Controls.Add(this.ViolationsListView);
            this.Controls.Add(this.ExceptionsLabel);
            this.Controls.Add(this.MainStatusStrip);
            this.Controls.Add(this.CloseButton);
            this.Name = "DisplayViolationsDialog";
            this.Load += new System.EventHandler(this.DisplayViolationsDialog_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button CloseButton;
        private System.Windows.Forms.StatusStrip MainStatusStrip;
        private System.Windows.Forms.Label ExceptionsLabel;
        private System.Windows.Forms.ListView ViolationsListView;
        private System.Windows.Forms.ColumnHeader RuleColumnHeader;
        private System.Windows.Forms.ColumnHeader MessageColumnHeader;
    }
}