// <auto-generated />
namespace Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Forms
{
    using Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls;

    partial class EditPolicyDialog
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditPolicyDialog));
            this.MainTabControl = new System.Windows.Forms.TabControl();
            this.GeneralTabPage = new System.Windows.Forms.TabPage();
            this.StyleCopGroupBox = new System.Windows.Forms.GroupBox();
            this.ExporStyleCopSettingsButton = new System.Windows.Forms.Button();
            this.LaunchStyleCopButton = new System.Windows.Forms.Button();
            this.ImportStyleCopSettingsButton = new System.Windows.Forms.Button();
            this.TreatErrorsAsLabel = new System.Windows.Forms.Label();
            this.TreatErrorsAsComboBox = new System.Windows.Forms.ComboBox();
            this.EvaluateOnGroupBox = new System.Windows.Forms.GroupBox();
            this.EvaluateOnRenameCheckBox = new System.Windows.Forms.CheckBox();
            this.EvaluateOnMergeCheckBox = new System.Windows.Forms.CheckBox();
            this.EvaluateOnBranchCheckBox = new System.Windows.Forms.CheckBox();
            this.EvaluateOnEditCheckBox = new System.Windows.Forms.CheckBox();
            this.EvaluateOnAddCheckBox = new System.Windows.Forms.CheckBox();
            this.AllowProjectOverrideCheckBox = new System.Windows.Forms.CheckBox();
            this.ExclusionsTabPage = new System.Windows.Forms.TabPage();
            this.ExclusionControl = new Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls.ExclusionManagerControl();
            this.StyleCopTabPage = new System.Windows.Forms.TabPage();
            this.CopyrightLabel = new System.Windows.Forms.Label();
            this.StyleCopAddressLabel = new System.Windows.Forms.Label();
            this.ProjectVersionLabel = new System.Windows.Forms.Label();
            this.ProjectNameLabel = new System.Windows.Forms.Label();
            this.StyleCopWebsiteNoticeLabel = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.MainTabControl.SuspendLayout();
            this.GeneralTabPage.SuspendLayout();
            this.StyleCopGroupBox.SuspendLayout();
            this.EvaluateOnGroupBox.SuspendLayout();
            this.ExclusionsTabPage.SuspendLayout();
            this.StyleCopTabPage.SuspendLayout();
            this.SuspendLayout();
            // 
            // SubmitButton
            // 
            resources.ApplyResources(this.SubmitButton, "SubmitButton");
            // 
            // AbortButton
            // 
            resources.ApplyResources(this.AbortButton, "AbortButton");
            // 
            // MainTabControl
            // 
            resources.ApplyResources(this.MainTabControl, "MainTabControl");
            this.MainTabControl.Controls.Add(this.GeneralTabPage);
            this.MainTabControl.Controls.Add(this.ExclusionsTabPage);
            this.MainTabControl.Controls.Add(this.StyleCopTabPage);
            this.MainTabControl.Name = "MainTabControl";
            this.MainTabControl.SelectedIndex = 0;
            // 
            // GeneralTabPage
            // 
            this.GeneralTabPage.Controls.Add(this.StyleCopGroupBox);
            this.GeneralTabPage.Controls.Add(this.TreatErrorsAsLabel);
            this.GeneralTabPage.Controls.Add(this.TreatErrorsAsComboBox);
            this.GeneralTabPage.Controls.Add(this.EvaluateOnGroupBox);
            this.GeneralTabPage.Controls.Add(this.AllowProjectOverrideCheckBox);
            resources.ApplyResources(this.GeneralTabPage, "GeneralTabPage");
            this.GeneralTabPage.Name = "GeneralTabPage";
            this.GeneralTabPage.UseVisualStyleBackColor = true;
            // 
            // StyleCopGroupBox
            // 
            this.StyleCopGroupBox.Controls.Add(this.ExporStyleCopSettingsButton);
            this.StyleCopGroupBox.Controls.Add(this.LaunchStyleCopButton);
            this.StyleCopGroupBox.Controls.Add(this.ImportStyleCopSettingsButton);
            resources.ApplyResources(this.StyleCopGroupBox, "StyleCopGroupBox");
            this.StyleCopGroupBox.Name = "StyleCopGroupBox";
            this.StyleCopGroupBox.TabStop = false;
            // 
            // ExporStyleCopSettingsButton
            // 
            resources.ApplyResources(this.ExporStyleCopSettingsButton, "ExporStyleCopSettingsButton");
            this.ExporStyleCopSettingsButton.Name = "ExporStyleCopSettingsButton";
            this.ExporStyleCopSettingsButton.UseVisualStyleBackColor = true;
            this.ExporStyleCopSettingsButton.Click += new System.EventHandler(this.ExporStyleCopSettingsButton_Click);
            // 
            // LaunchStyleCopButton
            // 
            resources.ApplyResources(this.LaunchStyleCopButton, "LaunchStyleCopButton");
            this.LaunchStyleCopButton.Name = "LaunchStyleCopButton";
            this.LaunchStyleCopButton.UseVisualStyleBackColor = true;
            this.LaunchStyleCopButton.Click += new System.EventHandler(this.LaunchStyleCopButton_Click);
            // 
            // ImportStyleCopSettingsButton
            // 
            resources.ApplyResources(this.ImportStyleCopSettingsButton, "ImportStyleCopSettingsButton");
            this.ImportStyleCopSettingsButton.Name = "ImportStyleCopSettingsButton";
            this.ImportStyleCopSettingsButton.UseVisualStyleBackColor = true;
            this.ImportStyleCopSettingsButton.Click += new System.EventHandler(this.ImportStyleCopSettingsButton_Click);
            // 
            // TreatErrorsAsLabel
            // 
            resources.ApplyResources(this.TreatErrorsAsLabel, "TreatErrorsAsLabel");
            this.TreatErrorsAsLabel.Name = "TreatErrorsAsLabel";
            // 
            // TreatErrorsAsComboBox
            // 
            this.TreatErrorsAsComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.TreatErrorsAsComboBox.FormattingEnabled = true;
            resources.ApplyResources(this.TreatErrorsAsComboBox, "TreatErrorsAsComboBox");
            this.TreatErrorsAsComboBox.Name = "TreatErrorsAsComboBox";
            // 
            // EvaluateOnGroupBox
            // 
            this.EvaluateOnGroupBox.Controls.Add(this.EvaluateOnRenameCheckBox);
            this.EvaluateOnGroupBox.Controls.Add(this.EvaluateOnMergeCheckBox);
            this.EvaluateOnGroupBox.Controls.Add(this.EvaluateOnBranchCheckBox);
            this.EvaluateOnGroupBox.Controls.Add(this.EvaluateOnEditCheckBox);
            this.EvaluateOnGroupBox.Controls.Add(this.EvaluateOnAddCheckBox);
            resources.ApplyResources(this.EvaluateOnGroupBox, "EvaluateOnGroupBox");
            this.EvaluateOnGroupBox.Name = "EvaluateOnGroupBox";
            this.EvaluateOnGroupBox.TabStop = false;
            // 
            // EvaluateOnRenameCheckBox
            // 
            resources.ApplyResources(this.EvaluateOnRenameCheckBox, "EvaluateOnRenameCheckBox");
            this.EvaluateOnRenameCheckBox.Name = "EvaluateOnRenameCheckBox";
            this.EvaluateOnRenameCheckBox.UseVisualStyleBackColor = true;
            // 
            // EvaluateOnMergeCheckBox
            // 
            resources.ApplyResources(this.EvaluateOnMergeCheckBox, "EvaluateOnMergeCheckBox");
            this.EvaluateOnMergeCheckBox.Name = "EvaluateOnMergeCheckBox";
            this.EvaluateOnMergeCheckBox.UseVisualStyleBackColor = true;
            // 
            // EvaluateOnBranchCheckBox
            // 
            resources.ApplyResources(this.EvaluateOnBranchCheckBox, "EvaluateOnBranchCheckBox");
            this.EvaluateOnBranchCheckBox.Name = "EvaluateOnBranchCheckBox";
            this.EvaluateOnBranchCheckBox.UseVisualStyleBackColor = true;
            // 
            // EvaluateOnEditCheckBox
            // 
            resources.ApplyResources(this.EvaluateOnEditCheckBox, "EvaluateOnEditCheckBox");
            this.EvaluateOnEditCheckBox.Name = "EvaluateOnEditCheckBox";
            this.EvaluateOnEditCheckBox.UseVisualStyleBackColor = true;
            // 
            // EvaluateOnAddCheckBox
            // 
            resources.ApplyResources(this.EvaluateOnAddCheckBox, "EvaluateOnAddCheckBox");
            this.EvaluateOnAddCheckBox.Name = "EvaluateOnAddCheckBox";
            this.EvaluateOnAddCheckBox.UseVisualStyleBackColor = true;
            // 
            // AllowProjectOverrideCheckBox
            // 
            resources.ApplyResources(this.AllowProjectOverrideCheckBox, "AllowProjectOverrideCheckBox");
            this.AllowProjectOverrideCheckBox.Name = "AllowProjectOverrideCheckBox";
            this.AllowProjectOverrideCheckBox.UseVisualStyleBackColor = true;
            // 
            // ExclusionsTabPage
            // 
            this.ExclusionsTabPage.Controls.Add(this.ExclusionControl);
            resources.ApplyResources(this.ExclusionsTabPage, "ExclusionsTabPage");
            this.ExclusionsTabPage.Name = "ExclusionsTabPage";
            this.ExclusionsTabPage.UseVisualStyleBackColor = true;
            // 
            // ExclusionControl
            // 
            this.ExclusionControl.DisableButtonVisible = false;
            this.ExclusionControl.EnableButtonVisible = false;
            this.ExclusionControl.ListViewTabStop = false;
            resources.ApplyResources(this.ExclusionControl, "ExclusionControl");
            this.ExclusionControl.Name = "ExclusionControl";
            this.ExclusionControl.AddingItem += new System.EventHandler<Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls.ItemEventArgs>(this.ExclusionControl_AddingItem);
            this.ExclusionControl.AddedItem += new System.EventHandler<System.EventArgs>(this.ExclusionControl_AddedItem);
            this.ExclusionControl.EditingItem += new System.EventHandler<Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls.ItemEventArgs>(this.ExclusionControl_EditingItem);
            this.ExclusionControl.EditedItem += new System.EventHandler<System.EventArgs>(this.ExclusionControl_EditedItem);
            this.ExclusionControl.RemovingItem += new System.EventHandler<Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls.ItemEventArgs>(this.ExclusionControl_RemovingItem);
            this.ExclusionControl.RemovedItem += new System.EventHandler<System.EventArgs>(this.ExclusionControl_RemovedItem);
            this.ExclusionControl.EnablingItem += new System.EventHandler<Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls.ItemEventArgs>(this.ExclusionControl_EnablingItem);
            this.ExclusionControl.DisablingItem += new System.EventHandler<Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls.ItemEventArgs>(this.ExclusionControl_DisablingItem);
            this.ExclusionControl.SelectedIndexChanged += new System.EventHandler<Gorba.Common.Tfs.Tools.StyleCopCheckInPolicy.UI.Controls.EnableButtonsEventArgs>(this.ExclusionControl_SelectedIndexChanged);
            // 
            // StyleCopTabPage
            // 
            this.StyleCopTabPage.Controls.Add(this.label1);
            this.StyleCopTabPage.Controls.Add(this.CopyrightLabel);
            this.StyleCopTabPage.Controls.Add(this.StyleCopAddressLabel);
            this.StyleCopTabPage.Controls.Add(this.ProjectVersionLabel);
            this.StyleCopTabPage.Controls.Add(this.ProjectNameLabel);
            this.StyleCopTabPage.Controls.Add(this.StyleCopWebsiteNoticeLabel);
            resources.ApplyResources(this.StyleCopTabPage, "StyleCopTabPage");
            this.StyleCopTabPage.Name = "StyleCopTabPage";
            this.StyleCopTabPage.UseVisualStyleBackColor = true;
            // 
            // CopyrightLabel
            // 
            resources.ApplyResources(this.CopyrightLabel, "CopyrightLabel");
            this.CopyrightLabel.Name = "CopyrightLabel";
            // 
            // StyleCopAddressLabel
            // 
            resources.ApplyResources(this.StyleCopAddressLabel, "StyleCopAddressLabel");
            this.StyleCopAddressLabel.ForeColor = System.Drawing.Color.Blue;
            this.StyleCopAddressLabel.Name = "StyleCopAddressLabel";
            this.StyleCopAddressLabel.Click += new System.EventHandler(this.StyleCopAddressLabel_Click);
            // 
            // ProjectVersionLabel
            // 
            resources.ApplyResources(this.ProjectVersionLabel, "ProjectVersionLabel");
            this.ProjectVersionLabel.Name = "ProjectVersionLabel";
            // 
            // ProjectNameLabel
            // 
            resources.ApplyResources(this.ProjectNameLabel, "ProjectNameLabel");
            this.ProjectNameLabel.Name = "ProjectNameLabel";
            // 
            // StyleCopWebsiteNoticeLabel
            // 
            resources.ApplyResources(this.StyleCopWebsiteNoticeLabel, "StyleCopWebsiteNoticeLabel");
            this.StyleCopWebsiteNoticeLabel.Name = "StyleCopWebsiteNoticeLabel";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // EditPolicyDialog
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.MainTabControl);
            this.Name = "EditPolicyDialog";
            this.Load += new System.EventHandler(this.EditPolicyDialog_Load);
            this.Controls.SetChildIndex(this.AbortButton, 0);
            this.Controls.SetChildIndex(this.SubmitButton, 0);
            this.Controls.SetChildIndex(this.MainTabControl, 0);
            this.MainTabControl.ResumeLayout(false);
            this.GeneralTabPage.ResumeLayout(false);
            this.GeneralTabPage.PerformLayout();
            this.StyleCopGroupBox.ResumeLayout(false);
            this.EvaluateOnGroupBox.ResumeLayout(false);
            this.EvaluateOnGroupBox.PerformLayout();
            this.ExclusionsTabPage.ResumeLayout(false);
            this.StyleCopTabPage.ResumeLayout(false);
            this.StyleCopTabPage.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl MainTabControl;
        private System.Windows.Forms.TabPage GeneralTabPage;
        private System.Windows.Forms.CheckBox AllowProjectOverrideCheckBox;
        private System.Windows.Forms.GroupBox EvaluateOnGroupBox;
        private System.Windows.Forms.CheckBox EvaluateOnEditCheckBox;
        private System.Windows.Forms.CheckBox EvaluateOnAddCheckBox;
        private System.Windows.Forms.CheckBox EvaluateOnBranchCheckBox;
        private System.Windows.Forms.CheckBox EvaluateOnRenameCheckBox;
        private System.Windows.Forms.CheckBox EvaluateOnMergeCheckBox;
        private System.Windows.Forms.TabPage ExclusionsTabPage;
        private ExclusionManagerControl ExclusionControl;
        private System.Windows.Forms.ComboBox TreatErrorsAsComboBox;
        private System.Windows.Forms.Label TreatErrorsAsLabel;
        private System.Windows.Forms.TabPage StyleCopTabPage;
        private System.Windows.Forms.Label StyleCopWebsiteNoticeLabel;
        private System.Windows.Forms.Button ImportStyleCopSettingsButton;
        private System.Windows.Forms.Button LaunchStyleCopButton;
        private System.Windows.Forms.Label ProjectVersionLabel;
        private System.Windows.Forms.Label ProjectNameLabel;
        private System.Windows.Forms.GroupBox StyleCopGroupBox;
        private System.Windows.Forms.Label StyleCopAddressLabel;
        private System.Windows.Forms.Label CopyrightLabel;
        private System.Windows.Forms.Button ExporStyleCopSettingsButton;
        private System.Windows.Forms.Label label1;
    }
}