//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Common.Configuration.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorba.Common.Configuration.Core.Tests.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Dictionary&gt;&lt;Language Index=&quot;0&quot; name=&quot;English&quot;&gt;&lt;Table Index=&quot;0&quot; Name=&quot;System&quot;&gt;&lt;Description&gt;Table containing all system information.&lt;/Description&gt;&lt;Column Index=&quot;0&quot; Name=&quot;Date&quot; /&gt;&lt;Column Index=&quot;1&quot; Name=&quot;Time&quot; /&gt;&lt;Column Index=&quot;2&quot; Name=&quot;Status&quot; /&gt;&lt;/Table&gt;&lt;Table Index=&quot;12&quot; Name=&quot;Stops&quot;&gt;&lt;Description&gt;Table containing all stop information.&lt;/Description&gt;&lt;Column Index=&quot;0&quot; Name=&quot;StopCity&quot; /&gt;&lt;Column Index=&quot;1&quot; Name=&quot;StopTime&quot; /&gt;&lt;/Table&gt;&lt;/Language&gt;&lt;Language Index=&quot;1&quot; Name=&quot;German&quot;&gt;&lt;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvalidXml {
            get {
                return ResourceManager.GetString("InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Dictionary&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element  maxOccurs=&quot;1&quot; minOccurs=&quot;1&quot; name=&quot;Languages&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element maxOccurs=&quot;unbounded&quot; minOccurs=&quot;1&quot; name=&quot;Language&quot;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:attribute nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;Dictionary&gt;&lt;Languages&gt;&lt;Language Index=&quot;0&quot; Name=&quot;English&quot; /&gt;&lt;Language Index=&quot;1&quot; Name=&quot;German&quot;/&gt;&lt;/Languages&gt;&lt;Tables&gt;&lt;Table Index=&quot;0&quot; Name=&quot;System&quot;&gt;&lt;Description&gt;Table containing all system information.&lt;/Description&gt;&lt;Column Index=&quot;0&quot; Name=&quot;Date&quot; /&gt;&lt;Column Index=&quot;1&quot; Name=&quot;Time&quot; /&gt;&lt;Column Index=&quot;2&quot; Name=&quot;Status&quot; /&gt;&lt;/Table&gt;&lt;Table Index=&quot;12&quot; Name=&quot;Stops&quot;&gt;&lt;Description&gt;Table containing all stop information.&lt;/Description&gt;&lt;Column Index=&quot;0&quot; Name=&quot;StopCity&quot; /&gt;&lt;Column Index=&quot;1&quot; Name= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidXml {
            get {
                return ResourceManager.GetString("ValidXml", resourceCulture);
            }
        }
    }
}
