//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Center.Media.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Images")]
        public string ImageExportPath {
            get {
                return ((string)(this["ImageExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Videos")]
        public string VideoExportPath {
            get {
                return ((string)(this["VideoExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxRecentResources {
            get {
                return ((int)(this["MaxRecentResources"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gorba\\Center\\Media\\ProjectPreviews")]
        public string ProjectPreviewsRelativePath {
            get {
                return ((string)(this["ProjectPreviewsRelativePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gorba\\Center\\Media\\Thumbnails")]
        public string AppDataThumbnailsRelativePath {
            get {
                return ((string)(this["AppDataThumbnailsRelativePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thumbnails")]
        public string ThumbnailsRelativePath {
            get {
                return ((string)(this["ThumbnailsRelativePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxRecentProjects {
            get {
                return ((int)(this["MaxRecentProjects"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gorba\\Center\\Media\\Resources")]
        public string AppDataResourcesRelativePath {
            get {
                return ((string)(this["AppDataResourcesRelativePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources")]
        public string ResourcesRelativePath {
            get {
                return ((string)(this["ResourcesRelativePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:01")]
        public global::System.TimeSpan PreviewPopupDelay {
            get {
                return ((global::System.TimeSpan)(this["PreviewPopupDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gorba.Center.Media.Core.Resources.Images.ImageNotAvailable.png")]
        public string VideoThumbnailPlaceholder {
            get {
                return ((string)(this["VideoThumbnailPlaceholder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UriVideoPlaceholder")]
        public string UriVideoThumbnailHash {
            get {
                return ((string)(this["UriVideoThumbnailHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://application:,,,/Resources/Images/Icons/video_44x44.png")]
        public string UriVideoThumbnail {
            get {
                return ((string)(this["UriVideoThumbnail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd.MM.yyyy")]
        public string DateEvalFormat {
            get {
                return ((string)(this["DateEvalFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hh\\:mm\\:ss")]
        public string TimeEvalFormat {
            get {
                return ((string)(this["TimeEvalFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pools")]
        public string PoolExportPath {
            get {
                return ((string)(this["PoolExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Symbols")]
        public string SymbolExportPath {
            get {
                return ((string)(this["SymbolExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fonts")]
        public string RelativeFontsFolderPath {
            get {
                return ((string)(this["RelativeFontsFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###")]
        public string CodeConversion_DefaultCode {
            get {
                return ((string)(this["CodeConversion_DefaultCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("codeconversion.csv")]
        public string CodeConversion_Filename {
            get {
                return ((string)(this["CodeConversion_Filename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Arial</string>
  <string>Ebrima</string>
  <string>Estrangelo Edessa</string>
  <string>Gadugi</string>
  <string>Gisha</string>
  <string>Impact</string>
  <string>Leelawadee</string>
  <string>Lucida Console</string>
  <string>Microsoft Sans Serif</string>
  <string>MoolBoran</string>
  <string>MV Boli</string>
  <string>Plantagenet Cherokee</string>
  <string>Segoe Script</string>
  <string>Segoe UI</string>
  <string>Segoe UI Symbol</string>
  <string>Symbol</string>
  <string>Tahoma</string>
  <string>Times New Roman</string>
  <string>Wingdings</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection InstalledFontList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InstalledFontList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" ({0})")]
        public string DuplicatedMediaPostfix {
            get {
                return ((string)(this["DuplicatedMediaPostfix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.jpg</string>
  <string>.jpeg</string>
  <string>.png</string>
  <string>.gif</string>
  <string>.bmp</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImageExtensions_Tft {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImageExtensions_Tft"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.asf</string>
  <string>.avi</string>
  <string>.mpg</string>
  <string>.mp2</string>
  <string>.mpeg</string>
  <string>.mp4</string>
  <string>.wmv</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VideoExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VideoExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EdgeSnapTolerance {
            get {
                return ((int)(this["EdgeSnapTolerance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:01")]
        public global::System.TimeSpan AudioPauseDefaultDuration {
            get {
                return ((global::System.TimeSpan)(this["AudioPauseDefaultDuration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sharon22k_HQ")]
        public string TtsDefaultVoice {
            get {
                return ((string)(this["TtsDefaultVoice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Audio")]
        public string AudioExportPath {
            get {
                return ((string)(this["AudioExportPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G07X07_2_GORBA_V1.FON")]
        public string DefaultAhdlcFontSmall {
            get {
                return ((string)(this["DefaultAhdlcFontSmall"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G16X07_2_GORBA_V2.FON")]
        public string DefaultAhdlcFontBig {
            get {
                return ((string)(this["DefaultAhdlcFontBig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LedDotRadius {
            get {
                return ((int)(this["LedDotRadius"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LedDotSpace {
            get {
                return ((int)(this["LedDotSpace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.egr</string>\r\n  <string>.egl</string>\r\n  <string>.egf</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection ImageExtensions_Led {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImageExtensions_Led"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateProjectOnStartup {
            get {
                return ((bool)(this["CreateProjectOnStartup"]));
            }
            set {
                this["CreateProjectOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20480")]
        public long ProjectSizeXmlPart {
            get {
                return ((long)(this["ProjectSizeXmlPart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime UpdateStartDate {
            get {
                return ((global::System.DateTime)(this["UpdateStartDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2100-12-31")]
        public global::System.DateTime UpdateEndDate {
            get {
                return ((global::System.DateTime)(this["UpdateEndDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HH\\:mm\\:ss")]
        public string TimeEvalConvertTimeSpanFormat {
            get {
                return ((string)(this["TimeEvalConvertTimeSpanFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfChar xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <char>32</char>
  <char>40</char>
  <char>41</char>
  <char>61</char>
  <char>36</char>
  <char>91</char>
  <char>93</char>
  <char>58</char>
  <char>59</char>
  <char>39</char>
</ArrayOfChar>")]
        public char[] InvalidFormulaNameChars {
            get {
                return ((char[])(this["InvalidFormulaNameChars"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string FontColor {
            get {
                return ((string)(this["FontColor"]));
            }
            set {
                this["FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string Font {
            get {
                return ((string)(this["Font"]));
            }
            set {
                this["Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int FontHeight {
            get {
                return ((int)(this["FontHeight"]));
            }
            set {
                this["FontHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int FontWeight {
            get {
                return ((int)(this["FontWeight"]));
            }
            set {
                this["FontWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int HourCenterX {
            get {
                return ((int)(this["HourCenterX"]));
            }
            set {
                this["HourCenterX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41")]
        public int HourCenterY {
            get {
                return ((int)(this["HourCenterY"]));
            }
            set {
                this["HourCenterY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public int HourHeight {
            get {
                return ((int)(this["HourHeight"]));
            }
            set {
                this["HourHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int HourWidth {
            get {
                return ((int)(this["HourWidth"]));
            }
            set {
                this["HourWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int HourX {
            get {
                return ((int)(this["HourX"]));
            }
            set {
                this["HourX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int HourY {
            get {
                return ((int)(this["HourY"]));
            }
            set {
                this["HourY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int HourZIndex {
            get {
                return ((int)(this["HourZIndex"]));
            }
            set {
                this["HourZIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HourHand.png")]
        public string HourFilename {
            get {
                return ((string)(this["HourFilename"]));
            }
            set {
                this["HourFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MinuteCenterX {
            get {
                return ((int)(this["MinuteCenterX"]));
            }
            set {
                this["MinuteCenterX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public int MinuteCenterY {
            get {
                return ((int)(this["MinuteCenterY"]));
            }
            set {
                this["MinuteCenterY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int MinuteHeight {
            get {
                return ((int)(this["MinuteHeight"]));
            }
            set {
                this["MinuteHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MinuteWidth {
            get {
                return ((int)(this["MinuteWidth"]));
            }
            set {
                this["MinuteWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61")]
        public int MinuteX {
            get {
                return ((int)(this["MinuteX"]));
            }
            set {
                this["MinuteX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int MinuteY {
            get {
                return ((int)(this["MinuteY"]));
            }
            set {
                this["MinuteY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MinuteZIndex {
            get {
                return ((int)(this["MinuteZIndex"]));
            }
            set {
                this["MinuteZIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MinuteHand.png")]
        public string MinuteFilename {
            get {
                return ((string)(this["MinuteFilename"]));
            }
            set {
                this["MinuteFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SecondsCenterX {
            get {
                return ((int)(this["SecondsCenterX"]));
            }
            set {
                this["SecondsCenterX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51")]
        public int SecondsCenterY {
            get {
                return ((int)(this["SecondsCenterY"]));
            }
            set {
                this["SecondsCenterY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public int SecondsHeight {
            get {
                return ((int)(this["SecondsHeight"]));
            }
            set {
                this["SecondsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int SecondsWidth {
            get {
                return ((int)(this["SecondsWidth"]));
            }
            set {
                this["SecondsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58")]
        public int SecondsX {
            get {
                return ((int)(this["SecondsX"]));
            }
            set {
                this["SecondsX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int SecondsY {
            get {
                return ((int)(this["SecondsY"]));
            }
            set {
                this["SecondsY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SecondsZIndex {
            get {
                return ((int)(this["SecondsZIndex"]));
            }
            set {
                this["SecondsZIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SecondsHand.png")]
        public string SecondsFilename {
            get {
                return ((string)(this["SecondsFilename"]));
            }
            set {
                this["SecondsFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".csv")]
        public string CsvMapping_DefaultExtension {
            get {
                return ((string)(this["CsvMapping_DefaultExtension"]));
            }
            set {
                this["CsvMapping_DefaultExtension"] = value;
            }
        }
    }
}
