//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Motion.Obc.Terminal.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MultiLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorba.Motion.Obc.Terminal.Gui.MultiLang", typeof(MultiLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88:88:88.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem3.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem4.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem2.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItem1.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Stop.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Stop.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Departure.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 8.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 5.
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAGRANGE.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L75.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L74.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 6.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 7.
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 4.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 3.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 2.
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 1.
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string _29 {
            get {
                return ResourceManager.GetString("_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +/- 0 min..
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control center.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMxMenuItem1.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re.
        /// </summary>
        internal static string _34 {
            get {
                return ResourceManager.GetString("_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuItem5.
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anschluss SBB abwarten.
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuItem1\nsecond.
        /// </summary>
        internal static string _37 {
            get {
                return ResourceManager.GetString("_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _38 {
            get {
                return ResourceManager.GetString("_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line1yp
        ///Line2yp
        ///Line3yp
        ///Line4yp.
        /// </summary>
        internal static string _39 {
            get {
                return ResourceManager.GetString("_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEO LAGRANGE.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string _44 {
            get {
                return ResourceManager.GetString("_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string _45 {
            get {
                return ResourceManager.GetString("_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string _46 {
            get {
                return ResourceManager.GetString("_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string _47 {
            get {
                return ResourceManager.GetString("_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string _48 {
            get {
                return ResourceManager.GetString("_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string _49 {
            get {
                return ResourceManager.GetString("_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOUISE MICHEL.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B:000000 Dr:0000 Ro:0000 Z:0000.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block:.
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line:.
        /// </summary>
        internal static string _54 {
            get {
                return ResourceManager.GetString("_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run:.
        /// </summary>
        internal static string _55 {
            get {
                return ResourceManager.GetString("_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Path:.
        /// </summary>
        internal static string _56 {
            get {
                return ResourceManager.GetString("_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        internal static string _57 {
            get {
                return ResourceManager.GetString("_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone:.
        /// </summary>
        internal static string _58 {
            get {
                return ResourceManager.GetString("_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver:.
        /// </summary>
        internal static string _59 {
            get {
                return ResourceManager.GetString("_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschrift - lblCaption.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid:.
        /// </summary>
        internal static string _60 {
            get {
                return ResourceManager.GetString("_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-Coord:.
        /// </summary>
        internal static string _61 {
            get {
                return ResourceManager.GetString("_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y-Coord:.
        /// </summary>
        internal static string _62 {
            get {
                return ResourceManager.GetString("_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000.
        /// </summary>
        internal static string _63 {
            get {
                return ResourceManager.GetString("_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000.
        /// </summary>
        internal static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00.
        /// </summary>
        internal static string _65 {
            get {
                return ResourceManager.GetString("_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +00°00&apos;00.00&quot;.
        /// </summary>
        internal static string _67 {
            get {
                return ResourceManager.GetString("_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS:.
        /// </summary>
        internal static string _68 {
            get {
                return ResourceManager.GetString("_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        internal static string _69 {
            get {
                return ResourceManager.GetString("_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        internal static string _70 {
            get {
                return ResourceManager.GetString("_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string _71 {
            get {
                return ResourceManager.GetString("_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations:.
        /// </summary>
        internal static string _72 {
            get {
                return ResourceManager.GetString("_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LST.
        /// </summary>
        internal static string _73 {
            get {
                return ResourceManager.GetString("_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Station.
        /// </summary>
        internal static string _74 {
            get {
                return ResourceManager.GetString("_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS.
        /// </summary>
        internal static string _75 {
            get {
                return ResourceManager.GetString("_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
    }
}
