//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorba.Center.Common.Wpf.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gorba.Center.Common.Wpf.Client.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password:.
        /// </summary>
        public static string ChangePassword_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePassword_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password does not match..
        /// </summary>
        public static string ChangePassword_Error_CurrentNoMatch {
            get {
                return ResourceManager.GetString("ChangePassword_Error_CurrentNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must consist of at least 8 characters..
        /// </summary>
        public static string ChangePassword_Error_InvalidPassword {
            get {
                return ResourceManager.GetString("ChangePassword_Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t change the password. If neccessary, try logging out and then back in with the old credentials..
        /// </summary>
        public static string ChangePassword_Error_NotChanged {
            get {
                return ResourceManager.GetString("ChangePassword_Error_NotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Failed.
        /// </summary>
        public static string ChangePassword_Error_NotChanged_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Error_NotChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new passwords don&apos;t match..
        /// </summary>
        public static string ChangePassword_Error_RepeatNoMatch {
            get {
                return ResourceManager.GetString("ChangePassword_Error_RepeatNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        public static string ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password:.
        /// </summary>
        public static string ChangePassword_RepeatPassword {
            get {
                return ResourceManager.GetString("ChangePassword_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CheckInDialog_Cancel {
            get {
                return ResourceManager.GetString("CheckInDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string CheckInDialog_Checkin {
            get {
                return ResourceManager.GetString("CheckInDialog_Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version comments must not be empty..
        /// </summary>
        public static string CheckInDialog_ErrorDescription_Empty {
            get {
                return ResourceManager.GetString("CheckInDialog_ErrorDescription_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Major version.
        /// </summary>
        public static string CheckInDialog_MajorVersion {
            get {
                return ResourceManager.GetString("CheckInDialog_MajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minor version.
        /// </summary>
        public static string CheckInDialog_MinorVersion {
            get {
                return ResourceManager.GetString("CheckInDialog_MinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string CheckInDialog_Skip {
            get {
                return ResourceManager.GetString("CheckInDialog_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Comments.
        /// </summary>
        public static string CheckInDialog_VersionComments {
            get {
                return ResourceManager.GetString("CheckInDialog_VersionComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of version would you like to check in?.
        /// </summary>
        public static string CheckInDialog_VersionTypeMessage {
            get {
                return ResourceManager.GetString("CheckInDialog_VersionTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection problem.
        /// </summary>
        public static string ConnectionException_DefaultTitle {
            get {
                return ResourceManager.GetString("ConnectionException_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the main window and resources.
        /// </summary>
        public static string LoadingWindow_BusyContent {
            get {
                return ResourceManager.GetString("LoadingWindow_BusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string Login_Authenticating {
            get {
                return ResourceManager.GetString("Login_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled.
        /// </summary>
        public static string Login_Cancel {
            get {
                return ResourceManager.GetString("Login_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error configuring connection to the server. Please contact the support team..
        /// </summary>
        public static string Login_CanNotGetConfiguration {
            get {
                return ResourceManager.GetString("Login_CanNotGetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Login_CanNotGetConfigurationTitle {
            get {
                return ResourceManager.GetString("Login_CanNotGetConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string Login_CheckingUpdates {
            get {
                return ResourceManager.GetString("Login_CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Login_Close {
            get {
                return ResourceManager.GetString("Login_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the server you would like to log in to and provide your credentials..
        /// </summary>
        public static string Login_Description {
            get {
                return ResourceManager.GetString("Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during validation.
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching tenants....
        /// </summary>
        public static string Login_FetchingTenants {
            get {
                return ResourceManager.GetString("Login_FetchingTenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to server..
        /// </summary>
        public static string Login_NoConnection {
            get {
                return ResourceManager.GetString("Login_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to services.
        /// </summary>
        public static string Login_NoServices {
            get {
                return ResourceManager.GetString("Login_NoServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tenants found.
        /// </summary>
        public static string Login_NoTenants {
            get {
                return ResourceManager.GetString("Login_NoTenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tenant found. Please choose another user..
        /// </summary>
        public static string Login_NoTenantsFound {
            get {
                return ResourceManager.GetString("Login_NoTenantsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tenant found.
        /// </summary>
        public static string Login_NoTenantsFoundTitle {
            get {
                return ResourceManager.GetString("Login_NoTenantsFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Login_OfflineButton {
            get {
                return ResourceManager.GetString("Login_OfflineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string Login_Server {
            get {
                return ResourceManager.GetString("Login_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find server. Check the server name..
        /// </summary>
        public static string Login_ServerNotFound {
            get {
                return ResourceManager.GetString("Login_ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t log in. The system is in maintenance mode:
        ///{0}.
        /// </summary>
        public static string Login_SystemInMaintenance {
            get {
                return ResourceManager.GetString("Login_SystemInMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is not available. Please try again later..
        /// </summary>
        public static string Login_SystemNotAvailable {
            get {
                return ResourceManager.GetString("Login_SystemNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t check for updates.
        /// </summary>
        public static string Login_UpdateError {
            get {
                return ResourceManager.GetString("Login_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authenticated.
        /// </summary>
        public static string Login_UserNotAuthenticated {
            get {
                return ResourceManager.GetString("Login_UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out from {0}.
        /// </summary>
        public static string Logout_ToolTipFormat {
            get {
                return ResourceManager.GetString("Logout_ToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maintenance mode for the background system has been activated. Please close your applications.
        ///Reason: {0}.
        /// </summary>
        public static string MaintenanceModeActivated_MessageFormat {
            get {
                return ResourceManager.GetString("MaintenanceModeActivated_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance mode.
        /// </summary>
        public static string MaintenanceModeActivated_Title {
            get {
                return ResourceManager.GetString("MaintenanceModeActivated_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not possible with the current user permissions..
        /// </summary>
        public static string Permission_NotGranted {
            get {
                return ResourceManager.GetString("Permission_NotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permission_NotGrantedTitle {
            get {
                return ResourceManager.GetString("Permission_NotGrantedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant:.
        /// </summary>
        public static string TenantSelection_LabelTenant {
            get {
                return ResourceManager.GetString("TenantSelection_LabelTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string TenantSelection_SelectButton {
            get {
                return ResourceManager.GetString("TenantSelection_SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your tenant..
        /// </summary>
        public static string TenantSelection_TenantDescription {
            get {
                return ResourceManager.GetString("TenantSelection_TenantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing an update from.
        /// </summary>
        public static string UpdateProgress_Description {
            get {
                return ResourceManager.GetString("UpdateProgress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading: {0:0.0}MB of {1:0.0}MB - {2}% complete.
        /// </summary>
        public static string UpdateProgress_Message {
            get {
                return ResourceManager.GetString("UpdateProgress_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password....
        /// </summary>
        public static string UserMenu_ChangePassword {
            get {
                return ResourceManager.GetString("UserMenu_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string UserMenu_Logout {
            get {
                return ResourceManager.GetString("UserMenu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: {0}.
        /// </summary>
        public static string UserMenu_ServerFormat {
            get {
                return ResourceManager.GetString("UserMenu_ServerFormat", resourceCulture);
            }
        }
    }
}
